apiVersion: v1
kind: Service
metadata:
  name: music-minimax-music3-api
spec:
  selector:
    app.kubernetes.io/name: music-minimax-music3-api
  ports:
    - name: http
      port: 8000
      targetPort: http
---
apiVersion: v1
kind: Service
metadata:
  name: music-uvr5-api
spec:
  selector:
    app.kubernetes.io/name: music-uvr5-api
  ports:
    - name: http
      port: 8000
      targetPort: http
---
apiVersion: v1
kind: Service
metadata:
  name: music-rvc-api
spec:
  selector:
    app.kubernetes.io/name: music-rvc-api
  ports:
    - name: http
      port: 8000
      targetPort: http
---
apiVersion: v1
kind: Service
metadata:
  name: music-audio-mixer-api
spec:
  selector:
    app.kubernetes.io/name: music-audio-mixer-api
  ports:
    - name: http
      port: 8000
      targetPort: http
---
apiVersion: v1
kind: Service
metadata:
  name: music-mcp-server
spec:
  selector:
    app.kubernetes.io/name: music-mcp-server
  ports:
    - name: http
      port: 8000
      targetPort: http

